apiVersion: v1
kind: Service
metadata:
  name: desafio-stone-janoti-service-gke
spec:
  selector:
    app: desafio-stone-janoti
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-stone-janoti-deployment-gke
spec:
  selector:
    matchLabels:
      app: desafio-stone-janoti
  replicas: 4
  template:
    metadata:
      labels:
        app: desafio-stone-janoti
    spec:
      containers:
      - name: desafio-stone-janoti
        imagePullPolicy: IfNotPresent
        image: gcr.io/stone-challenge-janoti/challenge-stone
        ports:
        - containerPort: 5000
