apiVersion: v1
kind: Service
metadata:
  name: desafio-stone-janoti-service
spec:
  selector:
    app: desafio-stone-janoti
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-stone-janoti-deployment
spec:
  selector:
    matchLabels:
      app: desafio-stone-janoti
  replicas: 4
  template:
    metadata:
      labels:
        app: desafio-stone-janoti
    spec:
      containers:
      - name: desafio-stone-janoti
        imagePullPolicy: Never
        image: challenge-stone
        ports:
        - containerPort: 5000
